USE [master]
GO
/****** Object:  Database [LMYFrameworkCore]    Script Date: 3/11/2019 4:04:15 PM ******/
CREATE DATABASE [LMYFrameworkCore]
 CONTAINMENT = NONE
GO
ALTER DATABASE [LMYFrameworkCore] SET COMPATIBILITY_LEVEL = 140
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [LMYFrameworkCore].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [LMYFrameworkCore] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [LMYFrameworkCore] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [LMYFrameworkCore] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [LMYFrameworkCore] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [LMYFrameworkCore] SET ARITHABORT OFF 
GO
ALTER DATABASE [LMYFrameworkCore] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [LMYFrameworkCore] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [LMYFrameworkCore] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [LMYFrameworkCore] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [LMYFrameworkCore] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [LMYFrameworkCore] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [LMYFrameworkCore] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [LMYFrameworkCore] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [LMYFrameworkCore] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [LMYFrameworkCore] SET  DISABLE_BROKER 
GO
ALTER DATABASE [LMYFrameworkCore] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [LMYFrameworkCore] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [LMYFrameworkCore] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [LMYFrameworkCore] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [LMYFrameworkCore] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [LMYFrameworkCore] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [LMYFrameworkCore] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [LMYFrameworkCore] SET RECOVERY FULL 
GO
ALTER DATABASE [LMYFrameworkCore] SET  MULTI_USER 
GO
ALTER DATABASE [LMYFrameworkCore] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [LMYFrameworkCore] SET DB_CHAINING OFF 
GO
ALTER DATABASE [LMYFrameworkCore] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [LMYFrameworkCore] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [LMYFrameworkCore] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'LMYFrameworkCore', N'ON'
GO
ALTER DATABASE [LMYFrameworkCore] SET QUERY_STORE = OFF
GO
USE [LMYFrameworkCore]
GO
ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO
USE [LMYFrameworkCore]
GO
/****** Object:  Table [dbo].[Roles]    Script Date: 3/11/2019 4:04:15 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Roles](
	[ID] [nvarchar](128) NOT NULL,
	[Name] [nvarchar](250) NOT NULL,
	[CreationDate] [datetime] NOT NULL,
	[ModifiedDate] [datetime] NOT NULL,
	[CreatedBy] [nvarchar](128) NOT NULL,
	[ModifiedBy] [nvarchar](128) NOT NULL,
 CONSTRAINT [PK_Roles] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[UserRoles]    Script Date: 3/11/2019 4:04:16 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UserRoles](
	[ID] [nvarchar](128) NOT NULL,
	[UserID] [nvarchar](128) NOT NULL,
	[RoleID] [nvarchar](128) NOT NULL,
	[CreationDate] [datetime] NOT NULL,
	[ModifiedDate] [datetime] NOT NULL,
	[CreatedBy] [nvarchar](128) NOT NULL,
	[ModifiedBy] [nvarchar](128) NOT NULL,
 CONSTRAINT [PK_UserRoles] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Users]    Script Date: 3/11/2019 4:04:16 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Users](
	[ID] [nvarchar](128) NOT NULL,
	[Email] [nvarchar](250) NOT NULL,
	[UserName] [nvarchar](250) NOT NULL,
	[Name] [nvarchar](250) NOT NULL,
	[PasswordHash] [nvarchar](1000) NOT NULL,
	[CreationDate] [datetime] NOT NULL,
	[ModifiedDate] [datetime] NOT NULL,
	[CreatedBy] [nvarchar](128) NOT NULL,
	[ModifiedBy] [nvarchar](128) NOT NULL,
 CONSTRAINT [PK_Users] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
INSERT [dbo].[Roles] ([ID], [Name],[CreationDate],[ModifiedDate],[CreatedBy],[ModifiedBy]) VALUES (N'SystemAdmin', N'System admin - مدير النظام',getdate(),getdate(),'admin','admin')
ALTER TABLE [dbo].[UserRoles]  WITH CHECK ADD  CONSTRAINT [FK_UserRoles_Roles] FOREIGN KEY([RoleID])
REFERENCES [dbo].[Roles] ([ID])
GO
ALTER TABLE [dbo].[UserRoles] CHECK CONSTRAINT [FK_UserRoles_Roles]
GO
ALTER TABLE [dbo].[UserRoles]  WITH CHECK ADD  CONSTRAINT [FK_UserRoles_Users] FOREIGN KEY([UserID])
REFERENCES [dbo].[Users] ([ID])
GO
ALTER TABLE [dbo].[UserRoles] CHECK CONSTRAINT [FK_UserRoles_Users]
GO
USE [master]
GO
ALTER DATABASE [LMYFrameworkCore] SET  READ_WRITE 
GO
